/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import bean.ClienteBean;
import bean.ProdutosBean;
import connection.ConnectionFactory;
import dao.ClienteDao;
import dao.ProdutosDao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        TextCliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextTelefone = new javax.swing.JLabel();
        TextEmail = new javax.swing.JLabel();
        cep = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        cod = new javax.swing.JTextField();
        telefone = new javax.swing.JTextField();
        TextNome1 = new javax.swing.JLabel();
        TextNome2 = new javax.swing.JLabel();
        TextNome3 = new javax.swing.JLabel();
        TextNome4 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        cpf = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        n = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BotãoSalvar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        TextNome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        endereco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de cadastro");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextCliente.setBackground(new java.awt.Color(255, 255, 255));
        TextCliente.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        TextCliente.setText("      Cadastro de Clientes");
        getContentPane().add(TextCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 345, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 105, 50));

        TextTelefone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextTelefone.setText("Telefone:");
        getContentPane().add(TextTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 60, 20));

        TextEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextEmail.setText("E-mail:");
        getContentPane().add(TextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 50, 20));

        cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepActionPerformed(evt);
            }
        });
        getContentPane().add(cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 123, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 111, -1));

        cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codActionPerformed(evt);
            }
        });
        getContentPane().add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 120, -1));

        telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneActionPerformed(evt);
            }
        });
        getContentPane().add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 108, -1));

        TextNome1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextNome1.setText("COD:");
        getContentPane().add(TextNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 40, 20));

        TextNome2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextNome2.setText("Nome:");
        getContentPane().add(TextNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 50, 20));

        TextNome3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextNome3.setText("CEP");
        getContentPane().add(TextNome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 20));

        TextNome4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextNome4.setText("CPF");
        getContentPane().add(TextNome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 111, -1));

        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });
        getContentPane().add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 123, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("<-");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 123, -1));

        jButton6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton6.setText("LIMPAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 215, 20, 23));

        BotãoSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BotãoSalvar.setText("SALVAR");
        BotãoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(BotãoSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 85, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("ATUALIZAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("PESQUISAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("EXCLUIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 490, 60));

        TextNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextNome.setText("N°");
        getContentPane().add(TextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 170, 20, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/FotoLogin1 - Cópia.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 360));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/FotoLogin1 - Cópia.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 440, 360));

        endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoActionPerformed(evt);
            }
        });
        getContentPane().add(endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepActionPerformed

    private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfActionPerformed

    private void codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
        new InternalFrame().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
        ClienteBean pb = new ClienteBean();
        ClienteDao  pd = new ClienteDao();
        
        int co = Integer.parseInt(JOptionPane.showInputDialog("Digite o código do produto:"));
        
        pb.setCod(co);
        
     pd.delete(pb);
        }catch(Exception i){
            
        }
   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BotãoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoSalvarActionPerformed
        
        try{
            ClienteBean pb = new ClienteBean();
        ClienteDao  pd = new ClienteDao();
        
        pb.setN(n.getText());
        pb.setCep(cep.getText());
        pb.setCpf(cpf.getText());
        pb.setCod(Integer.parseInt(cod.getText()));
        pb.setTelefone(telefone.getText());      
        pb.setEmail(email.getText());
        pb.setNome(nome.getText());
        /*pb.setNome(nome.getText());
	pb.setCod(Integer.parseInt(cod.getText()));	
        pb.setQtd(Integer.parseInt(qtd.getText()));
	pb.setForn(forn.getText());
        pb.setPreco(Double.parseDouble(preco.getText()));
	pb.setCat((String)cat.getSelectedItem());*/
       
        pd.create(pb);
        
        //cod.setText("");
        //nome.setText("");
        //qtd.setText("");
        //forn.setText("");
        //preco.setText("");
        //cat.setSelectedItem("");
               n.setText(null);
        cep.setText(null);
        cpf.setText(null);
        cod.setText(null);
        telefone.setText(null);
         endereco.setText(null);
        email.setText(null);
        nome.setText(null);
        
        }catch(Exception i){
            JOptionPane.showMessageDialog(null,"O N° e Cod Necessitam ser um valor inteiro");
        }
    }//GEN-LAST:event_BotãoSalvarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
             n.setText(null);
        cep.setText(null);
        cpf.setText(null);
        cod.setText(null);
        telefone.setText(null);
         endereco.setText(null);
        email.setText(null);
        nome.setText(null);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
        ClienteBean pb = new ClienteBean();
        ClienteDao  pd = new ClienteDao();
        int co = Integer.parseInt(JOptionPane.showInputDialog("Digite o Código do produto: "));
        
        pb.setCod(co);
        pb.setNome(nome.getText());
	pb.setCep(cep.getText() );
        pb.setCpf(cpf.getText()); 
pb.setTelefone(telefone.getText());
pb.setEndereco(endereco.getText());

pb.setN(n.getText());
pb.setEmail(email.getText());
        pd.Update(pb);
        
        cod.setText("");
	nome.setText("");
       
        }catch(Exception i){
            
        } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            
        
        ClienteBean pb = new ClienteBean();
        ClienteDao  pd = new ClienteDao();
        int co = Integer.parseInt(JOptionPane.showInputDialog("Digite o código do produto:"));
//      pd.findAll(id);
        Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;
       
        try {
            stmt = con.prepareStatement("SELECT * FROM cliente WHERE cod = "+co);
            rs = stmt.executeQuery();
            while(rs.next()){
                
        pb.setCod(rs.getInt("cod"));     
	pb.setNome(rs.getString("nome"));
	pb.setCep(rs.getString("cep"));
	pb.setTelefone(rs.getString("telefone"));
	pb.setEmail(rs.getString("email"));
        pb.setCpf(rs.getString("cpf"));
        pb.setN(rs.getString("n"));
        pb.setEndereco(rs.getString("endereco"));
        
	//pb.setCat((String)cat.getSelectedItem());	
	        
        
       

        cod.setText(String.valueOf(pb.getCod()));
        nome.setText(pb.getNome());
        telefone.setText(pb.getTelefone());
        n.setText(pb.getN());
        endereco.setText(pb.getEndereco());
        email.setText(pb.getEmail());
        cpf.setText(pb.getCpf());
        cep.setText(pb.getCep());
               
            }
        } catch (SQLException ex) {
            System.out.println("Pesquisa não deu certo!!");
        }finally{
            connection.ConnectionFactory.closeConnection(con, stmt, rs);
        }
       cod.setText(String.valueOf(pb.getCod()));
        nome.setText(pb.getNome());
        telefone.setText(pb.getTelefone());
        n.setText(pb.getN());
        endereco.setText(pb.getEndereco());
        email.setText(pb.getEmail());
        cpf.setText(pb.getCpf());
        cep.setText(pb.getCep());
        }catch(Exception i){
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotãoSalvar;
    private javax.swing.JLabel TextCliente;
    private javax.swing.JLabel TextEmail;
    private javax.swing.JLabel TextNome;
    private javax.swing.JLabel TextNome1;
    private javax.swing.JLabel TextNome2;
    private javax.swing.JLabel TextNome3;
    private javax.swing.JLabel TextNome4;
    private javax.swing.JLabel TextTelefone;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cep;
    private javax.swing.JTextField cod;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField email;
    private javax.swing.JTextField endereco;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField n;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField telefone;
    // End of variables declaration//GEN-END:variables
}
